#!/bin/sh
set -e

case "$1" in
  configure)
    # register the template unit (so systemd knows it exists)
    deb-systemd-helper enable inotibatch@.service >/dev/null

    # restart *previously enabled* instances
    for unit in /etc/systemd/system/*/*.wants/inotibatch@*.service; do
        unit=$(basename "$unit")
        if deb-systemd-helper was-enabled "$unit"; then
            echo "ℹ️ Restarting previously active service $unit"
            deb-systemd-helper start "$unit" >/dev/null || true
        fi
    done

    echo "✅ Inotibatch installed/updated."
    ;;
esac

#DEBHELPER#
exit 0
