#!/bin/sh
set -e

case "$1" in
  remove)
    deb-systemd-helper stop inotibatch@.service >/dev/null || true
    deb-systemd-helper disable inotibatch@.service >/dev/null
    ;;
esac

#DEBHELPER#
exit 0