#!/bin/bash
set -e

ln -sf /opt/inotibatch/logrotate/inotibatch /etc/logrotate.d/inotibatch
sed -i "s|/path/to/inotibatch.sh|/opt/inotibatch/bin/inotibatch.sh|g" /opt/inotibatch/systemd/inotibatch@.service
ln -sf /opt/inotibatch/systemd/inotibatch@.service /etc/systemd/system/

# Change ownership
chown -R root:root /opt/inotibatch
chown -R root:root /etc/inotibatch
chown -R root:root /var/log/inotibatch
chown root:root /usr/local/bin/inotibatch*

systemctl daemon-reexec || true
systemctl daemon-reload || true

echo "✅ Inotibatch installed. Configure via /etc/inotibatch/*.conf"
echo "ℹ️  Remember to run 'sudo inotibatch-create-services' after you created your config files to set up systemd services."
