#!/bin/bash
set -e

STATE_FILE="/var/lib/inotibatch/active_instances"

ln -sf /opt/inotibatch/logrotate/inotibatch /etc/logrotate.d/inotibatch
sed -i "s|/path/to/inotibatch.sh|/opt/inotibatch/bin/inotibatch.sh|g" /opt/inotibatch/systemd/inotibatch@.service
ln -sf /opt/inotibatch/systemd/inotibatch@.service /etc/systemd/system/

# Change ownership
chown -R root:root /opt/inotibatch
chown -R root:root /etc/inotibatch
chown -R root:root /var/log/inotibatch
chown root:root /usr/local/bin/inotibatch*

systemctl daemon-reexec || true
systemctl daemon-reload || true

if [ -f "$STATE_FILE" ]; then
  while read -r unit; do
    [ -n "$unit" ] && systemctl start "$unit"
  done < "$STATE_FILE"

  echo "ℹ️  Previously active services started again:"
  $(cat "$STATE_FILE")

  rm -f "$STATE_FILE"
else
  echo "ℹ️  No previously active services found. This is expected after the first install."
  echo "ℹ️  Run 'sudo inotibatch-create-services' after you created your config files to set up systemd services."
fi

echo "✅ Inotibatch installed/updated."
