#!/bin/sh
set -e

STATE_FILE="/tmp/inotibatch_active_instances"

# Alle laufenden Instanzen finden
systemctl list-units --type=service --state=active 'inotibatch@*.service' \
  | awk '/inotibatch@.*\.service/ {print $1}' > "$STATE_FILE"

exit 0